---
title: "R Notebook"
output: html_notebook
---

Old Data

```{r}
num_algorithms = 4
algorithm = list(num_algorithms)
algorithm[[1]] = read.csv("testresults1_NN.csv")
algorithm[[2]] = read.csv("testresults2_NN.csv")
algorithm[[3]] = read.csv("testresults3_NN.csv")
algorithm[[4]] = read.csv("testresults4_NN.csv")

#Statistics
for(floor in 0:2) {
  
  #Get the test cases on a certain floor for each algorithm
  floor_beac = list()
  for(i in 1:num_algorithms) {
    floor_beac[[i]] = algorithm[[i]][which(algorithm[[i]]$floor_true == floor),]
  }
  if(nrow(floor_beac[[1]]) == 0)
    next
  
  #Get the mean and std dev of each algorithm using 3 and 4 beacons
  for(n in 3:3) {
    
    for(i in 1:num_algorithms) {
        n_beac_1 = floor_beac[[i]][which(floor_beac[[i]]$top_n_beacons == n),]$error
        
        mean = mean(n_beac_1)
        stddev = sqrt(var(n_beac_1))
        
        string=paste0("(floor: ", floor, ", top n: ", n, ", algorithm: ", i, "): \n")
        string=paste0(string, "   mean 1:               ", mean, "\n")
        string=paste0(string, "   standard deviation 1: ", stddev, "\n")
        
        cat(string)
    }
  }
}

#Effectiveness
for(floor in 0:2) {
  
  #Get the test cases on a certain floor for each algorithm
  floor_beac = list()
  for(i in 1:num_algorithms) {
    floor_beac[[i]] = algorithm[[i]][which(algorithm[[i]]$floor_true == floor),]
  }
  if(nrow(floor_beac[[1]]) == 0)
    next
  
  #Compare the effectiveness of each algorithm using 3 and 4 beacons
  for(n in 3:3) {
    
    png(paste0(paste0("./Floor", floor, "_", n, "_beacons.png")))
    par(mfrow=c(4,4))
    
    #Compare the effectiveness of algorithm i against algorithm j
    for(i in 1:num_algorithms){
      for(j in 1:num_algorithms) {
        n_beac_1 = floor_beac[[i]][which(floor_beac[[i]]$top_n_beacons == n),]$error
        n_beac_2 = floor_beac[[j]][which(floor_beac[[j]]$top_n_beacons == n),]$error
        
        t_val = t.test(n_beac_1, n_beac_2, paired=TRUE)
        
        string=paste0("(floor: ", floor, ", top n: ", n, ", algorithms: ", i, " and ", j, "): \n")
        string=paste0(string, "   p Value:                ", t_val$p.value, "\n")
        
        cat(string)
        
        hist(n_beac_2 - n_beac_1, main = paste0(i, " v ", j), xlab="Error Difference (m)")
      }
    }
    
    dev.off()
  }
}

```

New Data - This file compares the effectiveness the new binning strategy as compared to the original binning strategy.

```{r}
num_algorithms = 8
algorithm = list(num_algorithms)
algorithm[[1]] = read.csv("testresults1_NN.csv")
algorithm[[2]] = read.csv("testresults2_NN.csv")
algorithm[[3]] = read.csv("testresults3_NN.csv")
algorithm[[4]] = read.csv("testresults4_NN.csv")
algorithm[[5]] = read.csv("testresults1_ON.csv")
algorithm[[6]] = read.csv("testresults2_ON.csv")
algorithm[[7]] = read.csv("testresults3_ON.csv")
algorithm[[8]] = read.csv("testresults4_ON.csv")

#Remove FAKE_TEST, FAKE_TEST_1, and FAKE_TEST_2
for(i in 1:8)
{
  algorithm[[i]] = algorithm[[i]][which(algorithm[[i]]$testid != "FAKE_TEST"),]
  algorithm[[i]] = algorithm[[i]][which(algorithm[[i]]$testid != "FAKE_TEST_2"),]
  algorithm[[i]] = algorithm[[i]][which(algorithm[[i]]$testid != "FAKE_TEST_3"),]
}

png("./Figure.png")
par(mfrow=c(2,2))

floor_beac = list()
floor_beac[[1]] = algorithm[[1]][which(algorithm[[1]]$floor_true == 1),]
floor_beac[[5]] = algorithm[[5]][which(algorithm[[5]]$floor_true == 1),]
n_beac_1 = floor_beac[[1]][which(floor_beac[[1]]$top_n_beacons == 3),]$error
n_beac_2 = floor_beac[[5]][which(floor_beac[[5]]$top_n_beacons == 3),]$error
t_val = t.test(n_beac_1, n_beac_2, paired=TRUE)
string=paste0("(algorithm: ", 1, "): \n")
string=paste0(string, "   p Value:                ", t_val$p.value, "\n")
string=paste0(string, "   mean alg1:              ", mean(floo))
cat(string)
hist(n_beac_2 - n_beac_1, breaks=100, main = paste0("Algorithm ", 1), xlab="Error Difference (m)")

floor_beac[[2]] = algorithm[[2]][which(algorithm[[2]]$floor_true == 1),]
floor_beac[[6]] = algorithm[[6]][which(algorithm[[6]]$floor_true == 1),]
n_beac_1 = floor_beac[[2]][which(floor_beac[[2]]$top_n_beacons == 3),]$error
n_beac_2 = floor_beac[[6]][which(floor_beac[[6]]$top_n_beacons == 3),]$error
t_val = t.test(n_beac_1, n_beac_2, paired=TRUE)
string=paste0("(algorithm: ", 2, "): \n")
string=paste0(string, "   p Value:                ", t_val$p.value, "\n")
cat(string)
hist(n_beac_2 - n_beac_1, breaks=5, main = paste0("Algorithm ", 2), xlab="Error Difference (m)")

floor_beac[[3]] = algorithm[[3]][which(algorithm[[3]]$floor_true == 1),]
floor_beac[[7]] = algorithm[[7]][which(algorithm[[7]]$floor_true == 1),]
n_beac_1 = floor_beac[[3]][which(floor_beac[[3]]$top_n_beacons == 3),]$error
n_beac_2 = floor_beac[[7]][which(floor_beac[[7]]$top_n_beacons == 3),]$error
t_val = t.test(n_beac_1, n_beac_2, paired=TRUE)
string=paste0("(algorithm: ", 3, "): \n")
string=paste0(string, "   p Value:                ", t_val$p.value, "\n")
cat(string)
hist(n_beac_2 - n_beac_1, breaks=100, main = paste0("Algorithm ", 3), xlab="Error Difference (m)")

floor_beac[[4]] = algorithm[[4]][which(algorithm[[4]]$floor_true == 1),]
floor_beac[[8]] = algorithm[[8]][which(algorithm[[8]]$floor_true == 1),]
n_beac_1 = floor_beac[[4]][which(floor_beac[[4]]$top_n_beacons == 3),]$error
n_beac_2 = floor_beac[[8]][which(floor_beac[[8]]$top_n_beacons == 3),]$error
t_val = t.test(n_beac_1, n_beac_2, paired=TRUE)
string=paste0("(algorithm: ", 4, "): \n")
string=paste0(string, "   p Value:                ", t_val$p.value, "\n")
cat(string)
hist(n_beac_2 - n_beac_1, breaks=100, main = paste0("Algorithm ", 4), xlab="Error Difference (m)")

dev.off()

```










